[tools]
go = "latest"

[tasks.rss]
description = "Generate RSS feeds"
run = "go run cmd/rss-builder/main.go"

[tasks.clean]
run = "go clean"

[tasks.fmt]
run = "go fmt ./..."

[tasks.vet]
depends = ["fmt"]
run = "go vet ./..."

[tasks.fix]
depends = ["fmt"]
run = "go fix ./..."

[tasks.staticcheck]
depends = ["fmt"]
run = "staticcheck ./..."

[tasks.govulncheck]
depends = ["fmt"]
run = "govulncheck ./..."


[tasks.check]
depends = ["vet", "fix", "staticcheck", "govulncheck"]

[tasks.build]
depends = ["fmt"]
run = "go build -o bin/rss-builder ./cmd/rss-builder"
